export const scaleFactor = 4;

export const dialogueData = {
  pc: `This is where I learn and study on my PCs. I learn security, OPSEC, OWASP, I am learning Python, and Java Script.  I currently know HTML 5, CSS, and Microsoft office products Word, Excel, and Power Point. I further dabble in ML/AI. <a href="https://github.com/SailAway33" target="_blank">Github</a>! `, 
  "cs-degree": `This is my SOC Cert I received from AntiSyphon Training, part of Black Hills Information Security, you can see it on my <a href="https://www.linkedin.com/in/andy-fontaine-97919327a" target="_blank"> Linked In</a> page.`,
  "sofa-table": `That's my sofa, where as a hobby I play with microproessers such as ESP 32, arduino style setups, and the RPI 2040 . Using MicroPython and C++. Watching my daughter make her first LEDSs blink was great.`,
  tv: `That's my TV. I've been watching tech security you tubers a lot recently like <a href="https://www.youtube.com/@BlackHillsInformationSecurity" target="_blank">Black Hills Information Security(BHIS),</a> <a href="https://www.youtube.com/@AntisyphonTraining" target="_blank">Antisyphon Training,</a>
  <a href="https://www.youtube.com/@freecodecamp" target="_blank">Free Code Camp,</a> (sometimes) and <a href="https://www.youtube.com/@MentalOutlaw" target="_blank">MentalOutlaw</a>!`,
  bed: `This where I rest. My mind never stops, so a lot of the time I listen to podcasts about learning new things to keep it company while I sleep. I enjoy podcasts from <a href="https://twit.tv/shows?shows_active=1" target="_blank"> This Week in Tech </a> one I love is Security Now with Steve Gibson. `,
  resume: `This is my desk and on it is my resume. <a href="./public/Andy-2R.pdf" target="_blank">Check it out?</a> Contact me at ASource33@proton.me if you have any job prospects`,
  projects: `This is one of my projects. I am learning JavaScript as a front end and learning to use Python to interact with the database SQL. This project has helped me learn Kaboom.js, and its interaction with HTML canvas. This is a work in progress. I learned it by watching tutorials by <a href="https://youtube.com/@jslegenddev" target="_blank">JS Legend dev </a> it is a work in progress as I learn the ins and outs.`,
  library: `There are a lot of books on my shelves. Many are cooking, science, and I also have learned a lot about the law especially administrative law.
  I love to read, and learn, I could sit and read an encyclopedia, it would help in trivia if there was a trivia for random knowledge. My library also includes how to build almost any project that has found my fancy. As I was a superintendent/foreman, and enjoy creating.`,
  exit: `This is where I go to ride my bicycle, it is partially electric. It helps to get outside and touch grass and do some exercise. If you want to exit my project, grab a bicycle and lets go touch some grass, or you can just close the tab.`,
};